import { Router } from "express";
import authRouter from "./auth.routes.js";
import appraisalCycleRouter from "./appraisal-cycle.routes.js";
import dashboardRouter from "./dashboard.routes.js";
import employeeManagementRouter from "./employee-management.routes.js";
import profileRequestRouter from "./profile-request.routes.js";
import meetingRouter from "./meeting.routes.js";
import pdpRouter from "./pdp.routes.js";
import selfReviewRouter from "./self-review.routes.js";
import peerReviewRouter from "./peer-review.routes.js";
import evaluationRouter from "./evaluation.routes.js";
import promotionRouter from "./promotion.routes.js";
import discussionMeetingRouter from "./discussion-meeting.routes.js";
import bonusRouter from "./bonus.routes.js";
import awardRouter from "./award.routes.js";
import pipRouter from "./pip.routes.js";
import followUpRouter from "./follow-up.routes.js";
import leadershipRouter from "./leadership.routes.js";

const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/employee-management", employeeManagementRouter);
apiRouter.use("/profile-requests", profileRequestRouter);
apiRouter.use("/meetings/discussions", discussionMeetingRouter);
apiRouter.use("/meetings", meetingRouter);
apiRouter.use("/pdps", pdpRouter);
apiRouter.use("/self-reviews", selfReviewRouter);
apiRouter.use("/peer-reviews", peerReviewRouter);
apiRouter.use("/evaluations", evaluationRouter);
apiRouter.use("/promotions", promotionRouter);
apiRouter.use("/bonuses", bonusRouter);
apiRouter.use("/awards", awardRouter);
apiRouter.use("/pips", pipRouter);
apiRouter.use("/follow-ups", followUpRouter);
apiRouter.use("/leadership", leadershipRouter);
apiRouter.use("/hr/appraisal-cycles", appraisalCycleRouter);

export default apiRouter;
